---
uni_links_domain_name: 'join.status.im'

uni_links_service_name: 'uni-links-handler'
uni_links_service_path: '/docker/{{ uni_links_service_name }}'
uni_links_compose_file: '{{ uni_links_service_path }}/docker-compose.yml'

# Container
uni_links_cont_image: 'statusteam/universal-links-handler:deploy'
uni_links_cont_name: '{{ uni_links_service_name }}'
uni_links_cont_port: 8092

# Generic container options
compose_recreate: 'smart'
compose_state: 'present'
compose_restart: false
