---
# Root password
bootstrap__root_pass: '{{lookup("bitwarden", "root-pass")}}'
# Consul encryption key
bootstrap__consul_encryption_key: '{{lookup("bitwarden", "consul", field="encryption-key")}}'

# CloudFlare Origin certificates
origin_certs:
  - domain: 'status.im'
    crt: '{{lookup("bitwarden", "CloudFlare/status.im", file="origin.crt")}}'
    key: '{{lookup("bitwarden", "CloudFlare/status.im", file="origin.key")}}'
    default: true
