---
# Root password
bootstrap__root_pass: '{{lookup("bitwarden", "root-pass")}}'
# Consul
bootstrap__consul_encryption_key: '{{lookup("bitwarden", "consul", field="encryption-key")}}'
bootstarp__consul_agent_acl_token: '{{lookup("bitwarden", "consul", field="agent-acl-token")}}'
# Wireguard
wireguard_consul_acl_token: '{{lookup("bitwarden", "consul", field="wireguard-acl-token")}}'

# CloudFlare
origin_certs:
  - domain: 'status.im'
    crt: '{{lookup("bitwarden", "CloudFlare/status.im", file="origin.crt")}}'
    key: '{{lookup("bitwarden", "CloudFlare/status.im", file="origin.key")}}'
    default: true
