---
- name: Configure uni-links
  hosts: uni-links
    - { role: origin-certs,      tags: origin-certs }
    - { role: uni-links-handler, tags: uni-links-handler }
    - { role: threatstack,       tags: threatstack }
