---
- name: Configure uni-links
  hosts: uni-links
  roles:
    - { role: origin-certs,      tags: origin-certs }
    - { role: uni-links-handler, tags: uni-links-handler }
    - { role: open-ports,        tags: open-ports }
    - { role: threatstack,       tags: threatstack }
