---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure uni-links
  hosts: uni-links
  roles:
    - { role: swap-file,         tags: swap-file }
    - { role: origin-certs,      tags: origin-certs }
    - { role: uni-links-handler, tags: uni-links-handler }
    - { role: nginx,             tags: nginx }
    - { role: open-ports,        tags: open-ports }
    - { role: threatstack,       tags: threatstack }
