---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: f2b061da8976444d6576b755578f0e799cde4372
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: d2eaa2d875f41d063e46eb6318270903315aab4d
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: b711bbabd2dc3d9ce8b1c3a6e5bc785901db9d09
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 7653d06cfc4d2613ee14bf637d38d98b0201864f
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: threatstack
  src: git@github.com:status-im/infra-role-threatstack.git
  version: 581bf6f1bd8b0d4873a77166b9ceb48a417565eb
  scm: git
