---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: 60587f86e085255b537cc37647003af105214d20
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 7d2646cad4046e20b02628f4efc1e2b87deef773
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: 2aa2627c9f01d5c08f43237a09dd3a7635592205
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 61a248a697d37c98b575be942bb6e86deb512380
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: threatstack
  src: git@github.com:status-im/infra-role-threatstack.git
  version: 552e60c1ab862ac8c73d4c9cba58e7f6f2261fdd
  scm: git
